### ISSUE TITLE
Part 4 and 5-Presentation/Lab Guide

### ISSUE THREAD

**Issue by bganeshmail** [007FFFLearning/MSDevSeriesSupport#1]
Team,

This is excellent session and nice initiative...Peter is genius in handling the content .

Please share Part 4 and 5-Presentation/Lab Guide

**Comment by pdtit** [comment]
Dear, we discovered some mistakes in the Docker commands in the lab guide, but it got replaced with an updated version just now. in meantime, you will also find the session we just finished 10min ago on here, including the cool ACR/ACI labs. Enjoy! And thanks for the great and awesome feedback on this series. very much appreciated! Best regards, Peter
